Run Trivy
Run entrypoint.sh
    entrypoint.sh
    shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
    env:
      AWS_REGION: ca-central-1
      ENVIRONMENT: develop
      TAG: b218562
      AWS_DEFAULT_REGION: ca-central-1
      AWS_ACCESS_KEY_ID: ***
      AWS_SECRET_ACCESS_KEY: ***
      AWS_SESSION_TOKEN: ***
      INPUT_SCAN_TYPE: image
      INPUT_IMAGE_REF: 286664220642.dkr.ecr.ca-central-1.amazonaws.com/microservice0-develop/userrepositoryservice:b218562
      INPUT_SCAN_REF: .
      INPUT_TRIVYIGNORES:
      INPUT_GITHUB_PAT:
      INPUT_LIMIT_SEVERITIES_FOR_SARIF:
      TRIVY_CACHE_DIR: /home/runner/work/microservice_0/microservice_0/.cache/trivy
  Building SARIF report with all severities
  Running Trivy with options: trivy image 286664220642.dkr.ecr.ca-central-1.amazonaws.com/microservice0-develop/userrepositoryservice:b218562
  2026-07-30T13:31:34Z	INFO	[vulndb] Need to update DB
  2026-07-30T13:31:34Z	INFO	[vulndb] Downloading vulnerability DB...
  2026-07-30T13:31:34Z	INFO	[vulndb] Downloading artifact...	repo="mirror.gcr.io/aquasec/trivy-db:2"
  23.91 MiB / 103.01 MiB [------------->______________________________________________] 23.21% ? p/s ?85.48 MiB / 103.01 MiB [------------------------------------------------->__________] 82.98% ? p/s ?103.01 MiB / 103.01 MiB [--------------------------------------------------------->] 100.00% ? p/s ?103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 131.84 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 131.84 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 131.84 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 123.33 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 123.33 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 123.33 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 115.38 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 115.38 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 115.38 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 107.93 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 107.93 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 107.93 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [------------------------------------------->] 100.00% 100.97 MiB p/s ETA 0s103.01 MiB / 103.01 MiB [-----------------------------------------------] 100.00% 33.54 MiB p/s 3.3s2026-07-30T13:31:39Z	INFO	[vulndb] Artifact successfully downloaded	repo="mirror.gcr.io/aquasec/trivy-db:2"
  2026-07-30T13:31:39Z	INFO	[vuln] Vulnerability scanning is enabled
  2026-07-30T13:31:39Z	INFO	[secret] Secret scanning is enabled
  2026-07-30T13:31:39Z	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
  2026-07-30T13:31:39Z	INFO	[secret] Please see https://trivy.dev/docs/v0.70/guide/scanner/secret#recommendation for faster secret detection
  2026-07-30T13:31:43Z	WARN	[dotnet] Multiple root projects found in .deps.json	existing_root="Shared.Protos/1.0.0" new_root="Shared.Common/1.0.0"
  2026-07-30T13:31:43Z	WARN	[dotnet] Multiple root projects found in .deps.json	existing_root="Shared.Protos/1.0.0" new_root="Shared.Contracts/1.0.0"
  2026-07-30T13:31:43Z	WARN	[dotnet] Multiple root projects found in .deps.json	existing_root="Shared.Protos/1.0.0" new_root="UserRepositoryService/1.0.0"
  2026-07-30T13:31:43Z	WARN	[dotnet] Multiple root projects found in .deps.json	existing_root="Shared.Protos/1.0.0" new_root="Shared.Logging/1.0.0"
  2026-07-30T13:31:44Z	INFO	Detected OS	family="debian" version="12.15"
  2026-07-30T13:31:44Z	INFO	[debian] Detecting vulnerabilities...	os_version="12" pkg_num=107
  2026-07-30T13:31:44Z	INFO	Number of language-specific files	num=3
  2026-07-30T13:31:44Z	INFO	[dotnet-core] Detecting vulnerabilities...
  2026-07-30T13:31:44Z	WARN	Using severities from other vendors for some vulnerabilities. Read https://trivy.dev/docs/v0.70/guide/scanner/vulnerability#severity-selection for details.

  📣 Notices:
    - Version 0.72.0 of Trivy is now available, current version is 0.70.0

  To suppress version checks, run Trivy scans with the --skip-version-check flag

  Error: Process completed with exit code 1.

Upload management scan results
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Run github/codeql-action/upload-sarif@v3
  with:
    sarif_file: trivy-management.sarif
    category: trivy-management
    checkout_path: /home/runner/work/microservice_0/microservice_0
    token: ***
    matrix: null
    wait-for-processing: true
  env:
    AWS_REGION: ca-central-1
    ENVIRONMENT: develop
    TAG: b218562
    AWS_DEFAULT_REGION: ca-central-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false
    CODEQL_ACTION_FEATURE_SANDWICH: false
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_VERSION: 3.37.3
    CODEQL_ACTION_DID_LOG_VERSION_DEPRECATION: true
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/deploy.yml:deploy
    CODEQL_WORKFLOW_STARTED_AT: 2026-07-30T13:31:44.629Z
    CODEQL_UPLOAD_SARIF_TRIVY_DATAACCESS__TRIVY: CODEQL_UPLOAD_SARIF_TRIVY_DATAACCESS__TRIVY
Error: Path does not exist: trivy-management.sarif